### ISSUE TITLE
Help me fix this problem

### ISSUE THREAD

**Issue by anhtahaylove** [dylannalex/tiktok_bot#1]
![image](https://user-images.githubusercontent.com/37265396/224978500-036f7d2a-add2-4378-a64a-9bb122cfed4c.png)

**Comment by dylannalex** [comment]
Hey @anhtahaylove, thanks for opening an issue. It seems like I forgot to upload a file to this repo. 

I have just fixed this issue. Please, be sure to update your tiktok_bot (download it again) so you don't have this error again.

**Comment by anhtahaylove** [comment]
> 

Thanks you!
